name: Someone Meowed?
# This workflow is triggered when an issue with the title "Meow!" is opened.

on:
  issues:
    types: [opened]

jobs:
  change-cat:
    if: ${{ github.event.issue.title == 'Meow!' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Remove existing images
        run: |
          rm -r images/*  
          
      - name: Install dependencies
        run: npm install axios moment
        
      - name: Create necessary directories
        run: |
          mkdir -p images
          
      - name: Create initial cat history if it doesn't exist
        run: |
          if [ ! -f cat-history.json ]; then
            echo '{"lastChangedBy": "@${{ github.event.issue.user.login}}", "timestamp": "2025-04-04T12:12:30Z", "formattedTimestamp": "2025-04-04 12:12:30"}' > cat-history.json
          fi

      - name: Change cat photo
        run: node .github/scripts/change-cat.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_CREATOR: ${{ github.event.issue.user.login }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add images/cat.jpg cat-history.json README.md
          git commit -m "Change cat photo (triggered by @${{ github.event.issue.user.login }})"
          git push
          
      - name: Close issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: "Pawsome! I've changed the cat photo for you. It was last changed by: @${{ github.event.issue.user.login }}. Meow!😸"